# Generated by Django 3.2.7 on 2021-10-16 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.achievements')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='фото')),
                ('achievements', models.ManyToManyField(blank=True, null=True, through='statistic.Awards', to='statistic.Achievements')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statistic.team')),
            ],
        ),
        migrations.CreateModel(
            name='Game2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField()),
                ('pts', models.IntegerField()),
                ('fgm2', models.IntegerField()),
                ('fga2', models.IntegerField()),
                ('fg2', models.IntegerField()),
                ('fgm3', models.IntegerField()),
                ('fga3', models.IntegerField()),
                ('fg3', models.IntegerField()),
                ('fgm', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('fg', models.IntegerField()),
                ('ftm', models.IntegerField()),
                ('fta', models.IntegerField()),
                ('ft', models.IntegerField()),
                ('oreb', models.IntegerField()),
                ('dreb', models.IntegerField()),
                ('reb', models.IntegerField()),
                ('ast', models.IntegerField()),
                ('tov', models.IntegerField()),
                ('stl', models.IntegerField()),
                ('blk', models.IntegerField()),
                ('eff', models.IntegerField()),
                ('plus_minus', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.player')),
            ],
        ),
        migrations.CreateModel(
            name='Game1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField()),
                ('pts', models.IntegerField()),
                ('fgm2', models.IntegerField()),
                ('fga2', models.IntegerField()),
                ('fg2', models.IntegerField()),
                ('fgm3', models.IntegerField()),
                ('fga3', models.IntegerField()),
                ('fg3', models.IntegerField()),
                ('fgm', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('fg', models.IntegerField()),
                ('ftm', models.IntegerField()),
                ('fta', models.IntegerField()),
                ('ft', models.IntegerField()),
                ('oreb', models.IntegerField()),
                ('dreb', models.IntegerField()),
                ('reb', models.IntegerField()),
                ('ast', models.IntegerField()),
                ('tov', models.IntegerField()),
                ('stl', models.IntegerField()),
                ('blk', models.IntegerField()),
                ('eff', models.IntegerField()),
                ('plus_minus', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.player')),
            ],
        ),
        migrations.AddField(
            model_name='awards',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.player'),
        ),
        migrations.CreateModel(
            name='AverageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField()),
                ('pts', models.IntegerField()),
                ('fgm2', models.IntegerField()),
                ('fga2', models.IntegerField()),
                ('fg2', models.IntegerField()),
                ('fgm3', models.IntegerField()),
                ('fga3', models.IntegerField()),
                ('fg3', models.IntegerField()),
                ('fgm', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('fg', models.IntegerField()),
                ('ftm', models.IntegerField()),
                ('fta', models.IntegerField()),
                ('ft', models.IntegerField()),
                ('oreb', models.IntegerField()),
                ('dreb', models.IntegerField()),
                ('reb', models.IntegerField()),
                ('ast', models.IntegerField()),
                ('tov', models.IntegerField()),
                ('stl', models.IntegerField()),
                ('blk', models.IntegerField()),
                ('eff', models.IntegerField()),
                ('plus_minus', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.player')),
            ],
        ),
    ]
