# Generated by Django 4.0 on 2021-12-08 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files_2_upload')),
            ],
        ),
        migrations.AddField(
            model_name='awards',
            name='year_awarded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='games_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='injured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rus_first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rus_last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_logo/%Y/%m/%d/', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='ast',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='blk',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='dreb',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='eff',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fg',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fg2',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fg3',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fga',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fga2',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fga3',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fgm',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fgm2',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fgm3',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='ft',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fta',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='ftm',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='min',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avg_stats', to='statistic.player'),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='oreb',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='plus_minus',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='pts',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='reb',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='stl',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='tov',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='ast',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='blk',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='dreb',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='eff',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='fg',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='fg2',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='fg3',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='fga',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='fga2',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='fga3',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='fgm',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='fgm2',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='fgm3',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='ft',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='fta',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='ftm',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='min',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats1', to='statistic.player'),
        ),
        migrations.AlterField(
            model_name='game1',
            name='oreb',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='plus_minus',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='pts',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='reb',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='stl',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='tov',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='ast',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='blk',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='dreb',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='eff',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='fg',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='fg2',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='fg3',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='fga',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='fga2',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='fga3',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='fgm',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='fgm2',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='fgm3',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='ft',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='fta',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='ftm',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='min',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats2', to='statistic.player'),
        ),
        migrations.AlterField(
            model_name='game2',
            name='oreb',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='plus_minus',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='pts',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='reb',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='stl',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='tov',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_players', to='statistic.team'),
        ),
        migrations.CreateModel(
            name='Game4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=1, max_digits=10)),
                ('pts', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fgm2', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fga2', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fg2', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fgm3', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fga3', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fg3', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fgm', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fga', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fg', models.DecimalField(decimal_places=1, max_digits=10)),
                ('ftm', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fta', models.DecimalField(decimal_places=1, max_digits=10)),
                ('ft', models.DecimalField(decimal_places=1, max_digits=10)),
                ('oreb', models.DecimalField(decimal_places=1, max_digits=10)),
                ('dreb', models.DecimalField(decimal_places=1, max_digits=10)),
                ('reb', models.DecimalField(decimal_places=1, max_digits=10)),
                ('ast', models.DecimalField(decimal_places=1, max_digits=10)),
                ('tov', models.DecimalField(decimal_places=1, max_digits=10)),
                ('stl', models.DecimalField(decimal_places=1, max_digits=10)),
                ('blk', models.DecimalField(decimal_places=1, max_digits=10)),
                ('eff', models.DecimalField(decimal_places=1, max_digits=10)),
                ('plus_minus', models.DecimalField(decimal_places=1, max_digits=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats4', to='statistic.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=1, max_digits=10)),
                ('pts', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fgm2', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fga2', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fg2', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fgm3', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fga3', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fg3', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fgm', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fga', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fg', models.DecimalField(decimal_places=1, max_digits=10)),
                ('ftm', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fta', models.DecimalField(decimal_places=1, max_digits=10)),
                ('ft', models.DecimalField(decimal_places=1, max_digits=10)),
                ('oreb', models.DecimalField(decimal_places=1, max_digits=10)),
                ('dreb', models.DecimalField(decimal_places=1, max_digits=10)),
                ('reb', models.DecimalField(decimal_places=1, max_digits=10)),
                ('ast', models.DecimalField(decimal_places=1, max_digits=10)),
                ('tov', models.DecimalField(decimal_places=1, max_digits=10)),
                ('stl', models.DecimalField(decimal_places=1, max_digits=10)),
                ('blk', models.DecimalField(decimal_places=1, max_digits=10)),
                ('eff', models.DecimalField(decimal_places=1, max_digits=10)),
                ('plus_minus', models.DecimalField(decimal_places=1, max_digits=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats3', to='statistic.player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
